CREATE TABLE Team
(
    team_id     int generated by default as identity primary key,
    name_leader varchar(100)                    not null UNIQUE,
    identifier  int check ( identifier > 1000 ) not null UNIQUE
);

CREATE TABLE Employee
(
    employee_id   int generated by default as identity primary key,
    team_id       int                                                         REFERENCES Team (team_id) on delete set null,
    employee_name varchar(100)                                                not null,
    birth_year    int check ( birth_year < 2030 ) check ( birth_year > 1900 ) not null,
    function      varchar(100)                                                not null
);